### ISSUE TITLE
Add a navbar

### ISSUE THREAD

**Issue by StevenN5** [zaanma/ProjectSE#2]
Add this in each file

    
    <nav class="navbar">
        <div class="logo">
            <a href="#">Team Project</a>
        </div>
        <ul class="nav-links">
            <li><a href="index.html">Home</a></li>
            <li><a href="About.html">About</a></li>
            <li><a href="Information.html">Information</a></li>
            <li><a href="project.html">Projects</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="login.html">Login</a></li>
        </ul>

**Comment by ZaanmaVerse** [comment]
oke done
